# -*- coding: utf-8 -*-
"""AP1_grafos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10u3f7PUPDOE-70pX6vgFv0-Zocg9c7oY

---

PROBLEMA **1** Item **1**

---
"""

print("Problema 1 Item 1")

vertices = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

arestas = [
    ('A', 'B'), ('A', 'C'), ('B', 'D'), ('C', 'D'),
    ('C', 'E'), ('D', 'F'), ('E', 'F'), ('F', 'G'),
    ('G', 'H'), ('H', 'I'), ('E', 'J')]

matriz_adj = [[0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
          [1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
          [1, 0, 0, 1, 1, 0, 0, 0, 0, 0],
          [0, 1, 1, 0, 0, 1, 0, 0, 0, 0],
          [0, 0, 1, 0, 0, 1, 0, 0, 0, 1],
          [0, 0, 0, 1, 1, 0, 1, 0, 0, 0],
          [0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
          [0, 0, 0, 0, 0, 0, 1, 0, 1, 0],
          [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
          [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],]


lista_adj = {}
for v in vertices:
    lista_adj[v] = []
for u, v in arestas:
    lista_adj[u].append(v)
    lista_adj[v].append(u)

print("LISTA ADJACÊNCIA")
for vertice, vizinhos in lista_adj.items():
    print(f"'{vertice}': {vizinhos},")

"""---

PROBLEMA **1** Item **2**

---
"""

print("Problema 1 Item 2")

def adj_para_matriz(lista_adj, vertices):
    mapa_indices = {vertice: i for i, vertice in enumerate(vertices)}
    num_vertices = len(vertices)
    matriz_adj = [[0] * num_vertices for _ in range(num_vertices)]

    for v_origem, vizinhos in lista_adj.items():
        idx_origem = mapa_indices[v_origem]
        for v_destino in vizinhos:
            idx_destino = mapa_indices[v_destino]
            matriz_adj[idx_origem][idx_destino] = 1
    return matriz_adj

def matriz_para_adj(matriz, vertices):
    lista_adj = {v: [] for v in vertices}
    n = len(vertices)
    for i in range(n):
        for j in range(n):
            if matriz[i][j] == 1:
                lista_adj[vertices[i]].append(vertices[j])
    return lista_adj

def arestas_para_matriz(arestas, vertices):
    n = len(vertices)
    idx = {v: i for i, v in enumerate(vertices)}
    matriz = [[0] * n for _ in range(n)]
    for u, v in arestas:
        matriz[idx[u]][idx[v]] = 1
        matriz[idx[v]][idx[u]] = 1
    return matriz

def matriz_para_arestas(matriz, vertices):
    arestas = []
    n = len(vertices)
    for i in range(n):
        for j in range(i + 1, n):
            if matriz[i][j] == 1:
                arestas.append((vertices[i], vertices[j]))
    return arestas

def lista_para_arestas(lista_adj):
    arestas = []
    vistos = set()
    for u, vizinhos in lista_adj.items():
        for v in vizinhos:
            if (v, u) not in vistos:
                arestas.append((u, v))
                vistos.add((u, v))
    return arestas

def arestas_para_lista_adj(arestas, vertices):
    lista_adj = {v: [] for v in vertices}
    for u, v in arestas:
        lista_adj[u].append(v)
        lista_adj[v].append(u)
    return lista_adj

def imprimir_lista_adj(lista_adj):
    for vertice, vizinhos in lista_adj.items():
        print(f"'{vertice}': {vizinhos},")

def imprimir_matriz(matriz):
    for linha in matriz:
        linha_str = " ".join(str(valor) for valor in linha)
        print(linha_str)


print("adj_para_matriz:")
imprimir_matriz(adj_para_matriz(lista_adj, vertices))
print()
print("matriz_para_adj:")
imprimir_lista_adj(matriz_para_adj(matriz_adj, vertices))
print()
print("arestas_para_matriz:")
imprimir_matriz(arestas_para_matriz(arestas, vertices))
print()
print("matriz_para_arestas:", matriz_para_arestas(matriz_adj, vertices))
print()
print("lista_para_arestas:", lista_para_arestas(lista_adj))
print()
print("arestas_para_lista_adj:")
imprimir_lista_adj(arestas_para_lista_adj(arestas, vertices))

"""---

PROBLEMA **1** Item **3**

---
"""

print("Problema 1 Item 3")

def estacoes_2_conexoes_lista(lista_adj, origem):
    nivel_1 = lista_adj[origem]
    nivel_2 = []
    for vertice in nivel_1:
        for vizinho in lista_adj[vertice]:
            if vizinho != origem and vizinho not in nivel_1 and vizinho not in nivel_2:
                nivel_2.append(vizinho)
    resultado = nivel_1 + nivel_2
    return resultado

def estacoes_2_conexoes_matriz(matriz, vertices, origem):
    i_origem = vertices.index(origem)
    nivel_1 = []
    for j in range(len(vertices)):
        if matriz[i_origem][j] == 1:
            nivel_1.append(vertices[j])
    nivel_2 = []
    for vertice in nivel_1:
        i = vertices.index(vertice)
        for j in range(len(vertices)):
            if matriz[i][j] == 1:
                vizinho = vertices[j]
                if vizinho != origem and vizinho not in nivel_1 and vizinho not in nivel_2:
                    nivel_2.append(vizinho)

    resultado = nivel_1 + nivel_2
    return resultado

def estacoes_2_conexoes_arestas(arestas, origem):
    nivel_1 = []
    for u, v in arestas:
        if u == origem:
            nivel_1.append(v)
        elif v == origem:
            nivel_1.append(u)
    nivel_2 = []
    for vertice in nivel_1:
        for u, v in arestas:
            if u == vertice and v != origem and v not in nivel_1 and v not in nivel_2:
                nivel_2.append(v)
            elif v == vertice and u != origem and u not in nivel_1 and u not in nivel_2:
                nivel_2.append(u)

    resultado = nivel_1 + nivel_2
    return resultado


print("Lista de adj: ", estacoes_2_conexoes_lista(lista_adj, 'A'))
print("Matriz de adj:", estacoes_2_conexoes_matriz(matriz_adj, vertices, 'A'))
print("Lista de arestas:    ", estacoes_2_conexoes_arestas(arestas, 'A'))

import timeit

n_repeticoes = 100000

tempo_lista = timeit.timeit(lambda: estacoes_2_conexoes_lista(lista_adj, 'A'), number=n_repeticoes)
tempo_matriz = timeit.timeit(lambda: estacoes_2_conexoes_matriz(matriz_adj, vertices, 'A'), number=n_repeticoes)
tempo_arestas = timeit.timeit(lambda: estacoes_2_conexoes_arestas(arestas, 'A'), number=n_repeticoes)

print()
print(f"Lista de adj:  {tempo_lista:.4f} segundos no total")
print(f"Matriz de adj: {tempo_matriz:.4f} segundos no total")
print(f"Lista de arestas:     {tempo_arestas:.4f} segundos no total")

"""---

Respotas PROBLEMA **1** Item **3**

---
3a) As estações B,C,D e E. Lista adjacente.

---

PROBLEMA **2**

---
"""

#PROBLEMA 2
print("Problema 2")

def vizinhos(grafo, v):
    return grafo[v]

def grau(grafo, v):
    return len(grafo[v])

def ha_aresta(grafo, u, v):
    return v in grafo[u]

print(vizinhos(lista_adj, 'A'))
print(grau(lista_adj, 'A'))
print(ha_aresta(lista_adj, 'A', 'B'))

"""---

PROBLEMA **3**

---
"""

#PROBLEMA 3
print("Problema 3")

def bfs(grafo, origem):
    visitado = {}
    distancia = {}
    antecessor = {}
    ordem = []
    for v in grafo:
        visitado[v] = False
        distancia[v] = -1
        antecessor[v] = None
    visitado[origem] = True
    distancia[origem] = 0
    fila = []
    fila.append(origem)
    while len(fila) > 0:
        u = fila[0]
        fila = fila[1:]
        ordem.append(u)
        for v in vizinhos(grafo, u):
            if visitado[v] == False:
                visitado[v] = True
                distancia[v] = distancia[u] + 1
                antecessor[v] = u
                fila.append(v)
    return ordem, distancia, antecessor

def construir_arvore(antecessor):
    arvore = {}
    for v in antecessor:
        arvore[v] = []
    for v, pai in antecessor.items():
        if pai is not None:
            arvore[pai].append(v)
    return arvore

def grau_arvore(arvore, v):
    return len(arvore[v])

ordem, distancia, antecessor = bfs(lista_adj, 'A')
arvore_bfs = construir_arvore(antecessor)

print("Ordem de descoberta:", ordem)
print()
print("Distancias ate A:")
for v in distancia:
    print(" ", v, "->", distancia[v])
print()
print("Antecessores:")
for v in antecessor:
    print(" ", v, "->", antecessor[v])
print()
print("ÁRVORE BFS")
for vertice, filhos in arvore_bfs.items():
    print(f"'{vertice}': {filhos},")
print()
print("GRAU DE CADA VÉRTICE (árvore BFS)")
print(f"{'Vértice':<10}{'Grau BFS':<12}")
for v in arvore_bfs:
    print(f"{v:<10}{grau_arvore(arvore_bfs, v):<12}")

"""

---

PROBLEMA **4**

---

"""

print("Problema 4")

def dfs(grafo, origem):
    visitado = {}
    antecessor = {}
    nivel = {}
    ordem = []
    for v in grafo:
        visitado[v] = False
        antecessor[v] = None
        nivel[v] = -1
    pilha = []
    pilha.append((origem, None, -1))
    while len(pilha) > 0:
        item = pilha[len(pilha) - 1]
        pilha = pilha[:len(pilha) - 1]
        u = item[0]
        pai = item[1]
        nivel_pai = item[2]
        if visitado[u] == False:
            visitado[u] = True
            antecessor[u] = pai
            nivel[u] = nivel_pai + 1
            ordem.append(u)
            lista_vizinhos = vizinhos(grafo, u)
            indice = len(lista_vizinhos) - 1
            while indice >= 0:
                v = lista_vizinhos[indice]
                if visitado[v] == False:
                    pilha.append((v, u, nivel[u]))
                indice = indice - 1
    return ordem, antecessor, nivel

def construir_arvore(antecessor):
    arvore = {}
    for v in antecessor:
        arvore[v] = []
    for v, pai in antecessor.items():
        if pai is not None:
            arvore[pai].append(v)
    return arvore

def grau_arvore(arvore, v):
    return len(arvore[v])

ordem, antecessor, nivel = dfs(lista_adj, 'A')
arvore_dfs = construir_arvore(antecessor)

print("Ordem de descoberta (DFS):", ordem)
print()
print("Antecessores:")
for v in antecessor:
    print(" ", v, "->", antecessor[v])
print("Niveis (profundidade na arvore de DFS):")
for v in nivel:
    print(" ", v, "->", nivel[v])
print()
print("ÁRVORE DFS")
for vertice, filhos in arvore_dfs.items():
    print(f"'{vertice}': {filhos},")
print()
print("GRAU DE CADA VÉRTICE (árvore DFS)")
print(f"{'Vértice':<10}{'Grau DFS':<12}")
for v in arvore_dfs:
    print(f"{v:<10}{grau_arvore(arvore_dfs, v):<12}")

"""Niveis (profundidade na arvore de BFS):
  A -> 0
  B -> 1
  C -> 1
  D -> 2
  E -> 2
  F -> 3
  G -> 4
  H -> 5
  I -> 6
  J -> 3

---


Niveis (profundidade na arvore de DFS):
  A -> 0
  B -> 1
  C -> 3
  D -> 2
  E -> 4
  F -> 5
  G -> 6
  H -> 7
  I -> 8
  J -> 5


---
GRAU DE CADA VÉRTICE
Vértice   Grau BFS    
A         2           - B         1           - C         1           - D         1           - E         1           - F         1           - G         1           - H         1           - I         0           - J         0           


Vértice   Grau DFS    
A         1      -     B         1      -     C         1      -     D         1      -     E         2       -    F         1     -      G         1  -        H         1     -      I         0       -    J         0      


---
Níveis: na BFS, o nível de cada vértice corresponde à sua distância mínima real até A. Na DFS, apenas A, B e D mantêm o mesmo nível; os demais vértices (C, E, F, G, H, I, J) ficam 2 níveis mais profundos, pois a DFS perde o atalho A->C, mergulhando primeiro pelo caminho A->B->D->C. Essa diferença aparece exatamente no único ciclo do grafo (A-B-D-C-A), onde existem caminhos de tamanhos diferentes até a raiz.
Grau: a BFS forma uma árvore mais "larga" perto da raiz — A tem grau 2 (ramifica direto para B e C) — enquanto a DFS forma uma árvore mais "linear": A tem grau 1, já que C deixa de ser filho de A e passa a ser filho de D. Em compensação, E ganha um filho a mais na DFS (F e J, grau 2) contra apenas J na BFS.


"""